#!/bin/bash

#ローカルタイムの設定
export TZ="Asia/Tokyo"

#ロケールの設定
export LANG="ja_JP.UTF-8"
export LC_CTYPE="ja_JP.UTF-8"
export LC_NUMERIC="ja_JP.UTF-8"
export LC_TIME="ja_JP.UTF-8"
export LC_MONETARY="ja_JP.UTF-8"
export LC_MESSAGES="ja_JP.UTF-8"
# export LC_ALL=ja_JP.UTF-8

#less
#LESSCHARSET="UTF-8"
#JLESSCHARSET="UTF-8"
export PAGER='less'
export LESS='-R'

export TERM=xterm-256color
# export TERM=tmux-256color
export XDG_CONFIG_HOME=~/.config

#Python
export PYTHON_HOME=/usr/local/python

#path
export PATH="$PATH:$PYTHON_HOME/bin"
export PATH="$PATH:/usr/local/bin:/bin:/usr/bin"
export PATH="$PATH:/usr/local/sbin:/sbin:/usr/sbin"
export PATH="$PATH:/usr/local/sh/system"

